#define R 'R'  // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA DERECHA SENTIDO HORARIO
#define L 'L'  // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA IZQUIERDA SENTIDO HORARIO
#define D 'D'  // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA INFERIOR SENTIDO HORARIO
#define U 'U'  // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA SUPERIOR SENTIDO HORARIO
#define B 'B'  // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA TRASERA SENTIDO HORARIO
#define FC 'F' // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA FRONTAL SENTIDO HORARIO
#define RA 'X' // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA DERECHA SENTIDO ANTI-HORARIO
#define LA 'Y' // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA IZQUIERDA SENTIDO ANTI-HORARIO
#define DA 'Z' // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA INFERIOR SENTIDO ANTI-HORARIO
#define UA 'V' // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA SUPERIOR SENTIDO ANTI-HORARIO
#define BA 'W' // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA TRASERA SENTIDO ANTI-HORARIO
#define FA 'N' // CARACTER QUE REPRESENTA EN LA SOLUCION UN MOVIMIENTO DE LA CARA FRONTAL SENTIDO ANTI-HORARIO


void setup() {
}

void loop() {

}
